### ISSUE TITLE
Use different colours on tasks on task page

### ISSUE THREAD

**Issue by sylvihuynh** [amalieeh/assessment-support#14]
There should be three different designs for the tasks based on the status of the assessment. These are:
- Finished
- Current
- Remaining

These boxes should route to the correct tasks.

**Comment by amalieeh** [comment]
Also
- [ ] Create functionality for saving and displaying which tasks have been assessed/are remaining.
The tasks that have been assessed should be temporary unclickable while as the remaining tasks are clickable and up for assessment.
