### ISSUE TITLE
Create a progress bar for the total remaining tasks/students within a task

### ISSUE THREAD

**Issue by sylvihuynh** [amalieeh/assessment-support#19]
The progressbar should display the total remaining tasks that are left for assessment within the current task.

**Comment by amalieeh** [comment]
This is on the evaluation page.

The progress bar does not necessarily show how many tasks that are left, but can show how consistent the evaluations are or more likely: a combination of the two.
This is up for discussion. :smile:

**Comment by amalieeh** [comment]
#82 Is better:)
