### ISSUE TITLE
Add information to header

### ISSUE THREAD

**Issue by sylvihuynh** [amalieeh/assessment-support#62]
Add "Besvarelser fra ulike kandidater" to header to make it more informative and intuitive that the user evaluates several student answers. 

Consider adding task number. The task number should be clearly on the page.

**Comment by sylvihuynh** [comment]
This will currently be on hold and considered after feedback on the new mini test. 

A solution could be to put information under the header but over the boxes, put color in the background of the all the boxes to make it stand more out and add the information as a title for this block.

**Comment by amalieeh** [comment]
This is fixed, but we might need the vg-idea later 👌
