### ISSUE TITLE
Remove picture-url from answer length

### ISSUE THREAD

**Issue by amalieeh** [amalieeh/assessment-support#77]
Now, short answers are bumped to an unrepresentative spot in the order of assessments to display.
E.g. a medium length answer is displayed first, with very long answers, because of en extremely long image URL. 
Suggestion is to check for words longer than e.g. 30 chars or if it begins with 'src="data:image/'. And if found then assume it is an url and remove it from the count.

**Comment by amalieeh** [comment]
can be in relation to #32

**Comment by sylvihuynh** [comment]
fixed together with #89
